language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm run docs:build
- npm run build
deploy:
  provider: pages:git
  token: $GITHUB_TOKEN
  local_dir: dist
  edge: true # opt in to dpl v2